### ISSUE TITLE
What means M and U acronyms in the check command?

### ISSUE THREAD

**Issue by panicoenlaxbox** [metadevpro/cenv#2]
Hi Pedro,

An interesting project :)

I have a doubt, what means M and U acronyms in the check command? I can guess that M is mismatch but U? And the number suffix, 1 and 2, what is the logic behind them?

**Comment by pjmolina** [comment]
Thanks @panicoenlaxbox !
M is for Mismatch and U is for Undefined. 
Just a initial seed for generating **unique codes** for each error type. There will be a table in the docs (TO DO) explaining the error codes like: U2 mean this.  etc.

For humans, the error description will be enough in most cases. 
But other tools consuming this one, can interpret these error codes and do awesome things with it like for example: autofix, retry a deployment, or alert/sent an email to somebody.
